camunda-community-hub/camunda-8-examples

.gitignore, zeebe-client/README.md, zeebe-client/pom.xml, zeebe-client/src/main/java/io/camunda/zeebe/example/cluster/TopologyViewer.java, zeebe-client/src/main/java/io/camunda/zeebe/example/data/HandleVariablesAsPojo.java, zeebe-client/src/main/java/io/camunda/zeebe/example/job/JobWorkerCreator.java, zeebe-client/src/main/java/io/camunda/zeebe/example/process/NonBlockingProcessInstanceCreator.java, zeebe-client/src/main/java/io/camunda/zeebe/example/process/ProcessDeployer.java, zeebe-client/src/main/java/io/camunda/zeebe/example/process/ProcessInstanceCreator.java, zeebe-client/src/main/java/io/camunda/zeebe/example/process/ProcessInstanceWithResultCreator.java, zeebe-client/src/main/resources/demoProcess.bpmn, zeebe-client/src/main/resources/demoProcessSingleTask.bpmn, zeebe-client/src/main/resources/log4j2.xml, zeebe-client/src/test/java/io/camunda/zeebe/example/DocsConsistencyTest.java
see https://github.com/camunda/zeebe/issues/9500
This adds the examples currently living in Zeebe repo to this project. The idea is to consolidate all examples in one place.
=> Moved Zeebe client example from Zeebe repository

twitter-review-java-springboot/src/main/resources/application.properties
Without a region I was getting `io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404`
=> Add example region in application.properties

weatherinfo-pyzeebe-connectors/README.md, weatherinfo-pyzeebe-connectors/src/activities.py, weatherinfo-pyzeebe-connectors/src/activitylookuptemplate.json, weatherinfo-pyzeebe-connectors/src/form.form, weatherinfo-pyzeebe-connectors/src/pyzeebeWorker.py, weatherinfo-pyzeebe-connectors/src/weatherinfo-process.bpmn
Connectors used:
* REST Connector
* Send Grid Connector
* Custom connector
=> Added a python example project that uses connector

synchronous-response-springboot/src/main/java/org/example/camunda/process/solution/worker/CalculateSomethingWorker.java
I've added some logstatements to follow the worker in the console output.
=> add output about worker invocation

.gitignore
Make the repository easier to use for eclipse users.
=> Ignore eclipse settings

.github/workflows/build.yaml, payment-example-process-application/README.md, payment-example-process-application/pom.xml, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/PaymentProcessApplication.java, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/rest/StartFormRestController.java, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/service/CreditCardExpiredException.java, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/service/CreditCardService.java, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/service/CustomerService.java, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/worker/CreditCardHandler.java, payment-example-process-application/src/main/java/com/camunda/consulting/web_shop_process_app/worker/CustomerCreditHandler.java, payment-example-process-application/src/main/resources/application.properties, payment-example-process-application/src/main/resources/check-payment.form, payment-example-process-application/src/main/resources/payment_process.bpmn, payment-example-process-application/src/main/resources/static/index.html, payment-example-process-application/src/main/resources/static/start-process.form, payment-example-process-application/src/test/java/com/camunda/consulting/web_shop_process_app/test/ProcessIntegrationTest.java, payment-example-process-application/src/test/java/com/camunda/consulting/web_shop_process_app/test/ServiceTest.java, payment-example-process-application/src/test/java/com/camunda/consulting/web_shop_process_app/test/WorkerTest.java, timer-testing/pom.xml, timer-testing/src/test/java/com/camunda/consulting/TimerTest.java
After listening to the challenges of a self-managed Camunda 8 installation, my idea was to provide an example application that you can put into the cluster not to start from scratch.
Posts like this: https://forum.camunda.io/t/camunda-8-components-in-eks-cluster-nodes/48952
plus additional discussions with customers and colleagues
And there is an example bundled in Camunda 7 as well.
=> initial version of example process application

.github/workflows/build.yaml
=> Update all builders to Java 21

payment-example-process-application/pom.xml
=> example process application: updated zeebe to 8.4

twitter-review-java-springboot/pom.xml
=> twitter review: example updated to 8.4

synchronous-response-springboot/README.md, synchronous-response-springboot/pom.xml, synchronous-response-springboot/src/main/java/org/example/camunda/process/solution/facade/ProcessController.java, synchronous-response-springboot/src/main/java/org/example/camunda/process/solution/worker/CalculateSomethingWorker.java, synchronous-response-springboot/src/test/java/org/example/camunda/process/solution/AppTest.java
=> moved to new api

.github/workflows/build.yaml
=> migrated all build jobs to temurin

timer-testing/pom.xml, timer-testing/src/main/java/com/camunda/consulting/ExampleApplication.java, timer-testing/src/main/resources/application.yaml, timer-testing/src/main/resources/get-up.bpmn, timer-testing/src/test/java/com/camunda/consulting/SpringTimerTest.java, timer-testing/src/test/java/com/camunda/consulting/TimerTest.java
Currently, timer testing is disabled. This PR re-enables it and increases stability
closes #204
=> fix timer testing

.github/workflows/build.yaml, element-template-generation/README.md, element-template-generation/element-templates/car-connector.json, element-template-generation/pom.xml, element-template-generation/src/main/java/com/camunda/consulting/CarConnector.java, element-template-generation/src/main/java/com/camunda/consulting/CarConnectorInput.java, element-template-generation/src/main/java/com/camunda/consulting/CarConnectorOutput.java, element-template-generation/src/main/resources/META-INF/services/io.camunda.connector.api.outbound.OutboundConnectorFunction, element-template-generation/src/test/java/com/camunda/consulting/CarConnectorTest.java, element-template-generation/src/test/java/com/camunda/consulting/ResultType.java, element-template-generation/src/test/java/com/camunda/consulting/TestApp.java, element-template-generation/src/test/resources/test.bpmn
=> Example: element template generation

README.md
=> remove outdated toc

timer-testing/pom.xml, timer-testing/src/main/resources/application.yaml
=> deps: update timer-testing to camunda 8.6

large-multi-instance-example/pom.xml, payment-example-process-application/pom.xml, payment-example-process-application/src/test/java/com/camunda/consulting/web_shop_process_app/test/ProcessUnitTest.java
=> migrated large mi example

payment-example-process-application/pom.xml, payment-example-process-application/src/test/java/com/camunda/consulting/web_shop_process_app/test/ProcessUnitTest.java
=> Fix flaky example process application test

large-multi-instance-example/src/main/resources/application.properties
=> update to new properties structure

event-processing/src/main/java/com/camunda/consulting/eventprocessing/EventController.java
=> remove annotation

extended-connector-runtime/pom.xml, extended-connector-runtime/src/main/resources/application.yaml, extended-connector-runtime/src/test/java/com/camunda/consulting/example/AppTest.java, extended-connector-runtime/src/test/resources/test.bpmn
=> made test independent from httpbin.org

element-template-generation/pom.xml
=> added spring boot dependencies

large-multi-instance-example/pom.xml, large-multi-instance-example/src/test/java/com/camunda/consulting/MultiInstanceTest.java, large-multi-instance-example/src/test/java/com/camunda/consulting/SimpleMultiInstanceTest.java
=> use spring sdk in version 8.7

async-service-task/pom.xml, large-multi-instance-example/pom.xml, parallel-operations/pom.xml, payment-example-process-application/pom.xml, react-tasklist/pom.xml, rollback-on-error-example/pom.xml, synchronous-response-springboot/pom.xml, timer-testing/pom.xml, twitter-review-java-springboot/pom.xml
=> Unify dependency properties

async-service-task/pom.xml, async-service-task/src/test/java/com/camunda/consulting/AsyncJobWorkerTest.java
=> use camunda process test

.github/workflows/build.yaml, payment-example-process-application/README.md, payment-example-process-application/kube/manifests/deployment.yaml, payment-example-process-application/pom.xml, payment-example-process-application/src/main/resources/check-payment.form, payment-example-process-application/src/main/resources/payment_process.bpmn, payment-example-process-application/src/test/java/com/camunda/consulting/web_shop_process_app/test/ProcessUnitTest.java
=> move payment example to 8.7

synchronous-response-springboot/pom.xml, synchronous-response-springboot/src/main/java/org/example/camunda/process/solution/SyncResponseProcessApplication.java, synchronous-response-springboot/src/test/java/org/example/camunda/process/solution/AppTest.java
=> move sync response to 8.7

camunda-client-plain-java/src/main/java/io/camunda/example/ClientProvider.java, camunda-client-plain-java/src/main/java/io/camunda/example/e2e/process/DeployAndComplete.java, camunda-client-plain-java/src/main/resources/exampleProcess.bpmn
This pull request adds support for two new authentication methods (Basic Auth and Camunda SaaS) to the `ClientProvider`, expands environment variable documentation, and introduces a complete end-to-end example demonstrating process deployment and job handling. The most important changes are listed below.
**Authentication Enhancements:**
* Added support for `basic` and `saas` authentication methods in `ClientProvider`, allowing connections using Basic Auth credentials or Camunda SaaS credentials. [[1]](diffhunk://#diff-2f2b3bcd6129e351970496ea9fafc4db25de456c7daf7230739387d099d36814L65-R126) [[2]](diffhunk://#diff-2f2b3bcd6129e351970496ea9fafc4db25de456c7daf7230739387d099d36814L88-R143)
* Expanded documentation in `ClientProvider` to specify required environment variables for each …
=> Add auth options

task-micro-frontend/pom.xml, task-micro-frontend/src/main/java/com/camunda/consulting/TaskService.java, task-micro-frontend/src/main/java/com/camunda/consulting/UpdateTaskDto.java, task-micro-frontend/src/main/resources/index.html
=> Micro frontend: added assign button
